### ISSUE TITLE
Why does Strider use git clone to sync a repository

### ISSUE THREAD

**Issue by thakerng** [Strider-CD/strider#682]
When I push to the repository from both Github and Bitbucket Why does Strider performs a hooks as `git clone` in preparing. It spend useless much time if I prefer `git pull` rather , how to edit the hooker, which module?

**Comment by keyvanfatehi** [comment]
@thakerng https://github.com/Strider-CD/strider-git/blob/master/worker.js

**Comment by thakerng** [comment]
The link above seems to be only git module ,editing In Facade which trigger to git module should be better

**Comment by knownasilya** [comment]
Probably because we don't want to deal with merging, and it also allows for fetching all submodules as well. It's a clean slate every time, instead of having to clean it up and then go through everything and pull it in.

**Comment by keyvanfatehi** [comment]
closing the issue since the original question in the title was answered by @knownasilya. hope that helps @thakerng -- feel free to submit PRs to the various projects (or create a brand new plugin if you think it is necessary) if you come up with something you believe to be an improvement. for example you could add an option to use git pull but have an automatic way to handle merge issues, etc. it could get hairy but the strider codebase is pretty easy to work with once you understand how the pieces fit together. feel free to ask more questions via the issues!
