### ISSUE TITLE
Error adding repo, user must have admin privileges (bitbucket)

### ISSUE THREAD

**Issue by nomean42** [Strider-CD/strider#888]
I do have admin rigths, but still can't add repo 
Screenshots:
http://joxi.ru/Y2LYpMDfy6JjA6
http://joxi.ru/brR5EJnC5KzeA1

**Comment by knownasilya** [comment]
Did you figure this out?

**Comment by nomean42** [comment]
Yes its okok now

**Comment by termax** [comment]
@nomean42  could you please share how ?

**Comment by nomean42** [comment]
@termax sorry, i dont remeber but it was smth like manually add privkey to bitbucket.

**Comment by termax** [comment]
@nomean42 thanks, cause i didn't manage to make it work automatically. Gave up yesterday and all the posts on this issue go to dead-end. First i had a problem with Auth permissions, but after i fixed it instead of admin privileges error i started getting error unknown. Thats it. It's a pity since i'm forced to work with github only because out of two integrations it's the one that works.
